# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Dr Lauren Ackerman"                                # Your name
  description: "Just Vibes (and linguistics)"   # A brief slogan (optional)
  image: img/headshot.png
  
  favicon: img/brainlogo.png
  twitter-card: 
    card-style: summary_large_image
  site-url: https://lmackerman.com
  google-analytics: "G-W3HSKMRKPX"
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/brainguage.png
    
    # your sub-pages
    left:
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Miscellaneous"
        href: miscellaneous/index.qmd
    
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:lauren.ackerman@ncl.ac.uk"  
      - icon: calendar-check-fill
        aria-label: calendly
        href: https://calendly.com/lauren-ackerman
      - icon: mortarboard-fill
        aria-label: googlescholar
        href: https://scholar.google.com/citations?user=XA5ggZQAAAAJ&hl=en&oi=ao
      - icon: github
        href: https://github.com/VerbingNouns/
 #     - icon: linkedin
 #       href: https://www.linkedin.com/in/lauren-ackerman-3b1aa7b8/
      - icon: flower3
        aria-label: osf
        href: https://osf.io/f9qeg/  
      - icon: twitter
        href: https://twitter.com/VerbingNouns
      - icon: clock-fill
        aria-label: timezone
        href: https://www.timeanddate.com/worldclock/uk/newcastle-upon-tyne
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block"></span>
    center: |
      <span class="faux-block">&#169; 2023 Lauren Ackerman</span>
    right: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">Template: &#169; 2023 Marvin Schmitt CC BY-SA 4.0</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true